fix(): omit empty license key in txAdmin mode

diff --git a/entrypoint b/entrypoint
--- a/entrypoint
+++ b/entrypoint
@@ -33,17 +33,19 @@ if [ -z "${NO_LICENSE_KEY}${NO_LICENCE_KEY}" ]; then
         LICENSE_KEY="${LICENCE_KEY}"
     fi
 
-    if [ -z "${NO_DEFAULT_CONFIG}" ] && [ -z "${LICENSE_KEY}" ]; then
-        >&2 printf "License key not found in environment, please create one at https://keymaster.fivem.net!\n"
-        exit 1
-    fi
+    if [ -n "${NO_DEFAULT_CONFIG}" ]; then
+        if [ -n "${LICENSE_KEY}" ]; then
+            >&2 printf "txAdmin does not use the \$LICENSE_KEY environment variable.\nPlease remove it and set it through the txAdmin web UI.\n\n"
+            exit 1
+        fi
+    else
+        if [ -z "${LICENSE_KEY}" ]; then
+            >&2 printf "License key not found in environment, please create one at https://keymaster.fivem.net!\n"
+            exit 1
+        fi
 
-    if [ -z "${CONFIG_ARGS}" ] && [ -n "${LICENSE_KEY}" ] && [ -n "${NO_DEFAULT_CONFIG}" ]; then
-        >&2 printf "txadmin does not use the \$LICENSE_KEY environment variable.\nPlease remove it and set it through the txadmin web UI\n\n"
-        exit 1
+        CONFIG_ARGS="$CONFIG_ARGS +set sv_licenseKey ${LICENSE_KEY}"
     fi
-
-    CONFIG_ARGS="$CONFIG_ARGS +set sv_licenseKey ${LICENSE_KEY}"
 fi
 
 exec /lib/ld-musl-x86_64.so.1 \
